apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-java-app
  namespace: development
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  selector:
    matchLabels:
      app: simple-java-app
  template:
    metadata:
      labels:
        app: simple-java-app
    spec:
      containers:
      - name: simple-java-app
        image: docker.io/riturajmishra662/java-springboot-microservice:latest
        ports:
        - containerPort: 8080
